DECLARE
  P_MEMBERNAME VARCHAR2(100);
  P_PASSWORD VARCHAR2(100);
  P_TEL VARCHAR2(15);
  O_MEMBERID VARCHAR2(50);
BEGIN
  P_MEMBERNAME := NULL;
  P_PASSWORD := NULL;
  P_TEL := NULL;

  FIND_MEMBER_ID(
    P_MEMBERNAME => P_MEMBERNAME,
    P_PASSWORD => P_PASSWORD,
    P_TEL => P_TEL,
    O_MEMBERID => O_MEMBERID
  );
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('O_MEMBERID = ' || O_MEMBERID);
*/ 
  :O_MEMBERID := O_MEMBERID;
rollback; 
END;
