DECLARE
  P_MEMBER_NAME VARCHAR2(200);
  P_PASSWORD VARCHAR2(200);
  P_TEL VARCHAR2(200);
  P_MEMBER_ID VARCHAR2(200);
BEGIN
  P_MEMBER_NAME := NULL;
  P_PASSWORD := NULL;
  P_TEL := NULL;

  FIND_MEMBER_ID(
    P_MEMBER_NAME => P_MEMBER_NAME,
    P_PASSWORD => P_PASSWORD,
    P_TEL => P_TEL,
    P_MEMBER_ID => P_MEMBER_ID
  );
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('P_MEMBER_ID = ' || P_MEMBER_ID);
*/ 
  :P_MEMBER_ID := P_MEMBER_ID;
--rollback; 
END;
